#!/bin/bash
s1='K_carrageenan_4_1881_pixel_reconstruction_1x_binned_Slice_'
echo $s1
outp='KCar4_1x'
outdir='./results_'$outp
echo $outdir
mkdir $outdir
for ((i=2;i<96;i++))
do
	s2=$s1$i
	echo $s2
    s3='/home/phc/DATA/stack_to_images/'$s2'.tif'
    outfile=$outdir'/slice_'$i
	echo $s3
    /bin/bash -c './SAXSsim -i '"$s3"' -j 12 -o '"$outfile"''
done
